const router = require("express").Router();
const { Product, User } = require("../models/");
const stripe = require("stripe")(
  "sk_test_51KGGcjDQw3iOHoMjf3YITBwKINTnXK3bur0cgCPuh60dD993ZmOU4Tqoy33u52gPG3usHBJpeZnvJBHuQtUxRK5O00WkMZpfof"
);

router.get("/", (req, res) => {
  res.render("index");
});
//need to add get from product table
// router.get("/products", (req, res) => {
//   // where is /products at in my code ?  it
//   res.render("products");
// });

//get all products from database
router.get("/products", (req, res) => {
  Product.findAll({
    // include: [User],
  })
    .then((dbProductData) => {
      const products = dbProductData.map((post) => post.get({ plain: true }));

      res.render("products", { products });
      console.log(products);
    })
    .catch((err) => {
      console.log(err);
      res.status(500).json(err);
    });
});

//sequelize findByPk method
router.get("/product/:id", (req, res) => {
  Product.findByPk(req.params.id)
    .then((dbProductData) => {
      const product = dbProductData.get({ plain: true });
      res.render("single-product", { product });
    })
    .catch((err) => {
      console.log(err);
      res.status(500).json(err);
    });
});

//get the data-amount from the form in  product.handlebars and pass it in to this post route
router.post("/charge", (req, res) => {
  const { price, stripeToken } =
    //stripeToken is the token that is generated by stripe when you click on the button
    //price is the amount of the product that is being charged from the form
    req.body;
  console.log(price);
  console.log(stripeToken);
  stripe.charges
    .create({
      amount: price,
      source: stripeToken,
      currency: "usd",
    })
    .then((charge) => res.render("success"));
});

router.get("/contact_me", (req, res) => {
  res.render("contact");
});

router.get("/login", (req, res) => {
  res.render("registration");
});

router.get("/privacy", (req, res) => {
  res.render("privacy");
});

router.get("/welcomeuser", (req, res) => {
  res.render("welcomeuser");
});

//admin page
router.get("/admin", (req, res) => {
  res.render("admin");
});

//router.get for the a href product 1 inside the productinfo1.handlebars

//TODO after login

module.exports = router;
